import { jsonResponse } from '../cors.js';
import { log, logError } from '../utils.js';
import { getSession, verifySessionSecret } from '../sessions.js';
import { getSessionIdFromCookie } from '../cookies.js';
import { callClaude } from '../claude.js';
import { INTERVIEW_KIT_SYSTEM_PROMPT } from '../prompts/interviewKit.js';

/**
 * Generates an interview kit for the given CV and job description.
 * Pure generation — no KV caching, no session lookup.
 * Throws on Claude error or truncation; callers are responsible for caching.
 *
 * @param {string} cvText
 * @param {string} jobDesc
 * @param {string} language — 'id' | 'en'
 * @param {object} env
 * @returns {Promise<object>} parsed interview kit
 */
export async function generateInterviewKit(cvText, jobDesc, language, env) {
  const langLabel   = language === 'en' ? 'English' : 'Bahasa Indonesia';
  const userContent = `Language: ${language}\nCandidate CV:\n${cvText}\n\nJob Description:\n${jobDesc}\n\nGenerate the interview kit. All generated text (email, WhatsApp, tell_me_about_yourself, sample_answer) must be in ${langLabel}.`;

  const claudeResponse = await callClaude(env, INTERVIEW_KIT_SYSTEM_PROMPT, userContent, 3000);

  if (claudeResponse.stop_reason === 'max_tokens') {
    throw new Error('Respons AI terpotong. Coba lagi.');
  }

  const raw   = claudeResponse.content[0].text;
  const start = raw.indexOf('{');
  const end   = raw.lastIndexOf('}');
  if (start === -1 || end === -1) throw new Error('Respons AI tidak valid.');
  return JSON.parse(raw.slice(start, end + 1));
}

export async function handleInterviewKit(request, env) {
  const session_id = getSessionIdFromCookie(request);
  if (!session_id) {
    return jsonResponse({ message: 'Sesi tidak ditemukan. Pastikan browser mengizinkan cookies.' }, 401, request, env);
  }

  let body;
  try {
    body = await request.json();
  } catch {
    body = {};
  }

  const rawLang  = body.language;
  const language = rawLang === 'en' ? 'en' : 'id';

  // Cache-first: the kit may have been pre-generated by /generate and cached under
  // kit_${session_id}_id. Serving from cache doesn't require an active session,
  // which allows single-credit users to fetch their kit after session deletion.
  const cacheKey = `kit_${session_id}_${language}`;
  try {
    const cached = await env.GASLAMAR_SESSIONS.get(cacheKey, { type: 'json' });
    if (cached) {
      log('interview_kit_cache_hit', { session_id, language });
      return jsonResponse({ success: true, kit: cached }, 200, request, env);
    }
  } catch {
    // proceed to session lookup
  }

  // Cache miss — need a live session to generate
  const session = await getSession(env, session_id);
  if (!session) {
    return jsonResponse({ message: 'Sesi tidak ditemukan atau sudah kedaluwarsa' }, 404, request, env);
  }

  const providedSecret = request.headers.get('X-Session-Secret');
  if (!await verifySessionSecret(session, providedSecret)) {
    return jsonResponse({ message: 'Akses ditolak: token sesi tidak valid' }, 403, request, env);
  }

  const { cv_text, job_desc } = session;
  if (!cv_text || !job_desc) {
    return jsonResponse({ message: 'Data sesi tidak lengkap' }, 400, request, env);
  }

  try {
    const parsedKit = await generateInterviewKit(cv_text, job_desc, language, env);

    await env.GASLAMAR_SESSIONS.put(cacheKey, JSON.stringify(parsedKit), { expirationTtl: 86400 });

    log('interview_kit_generated', { session_id, language });
    return jsonResponse({ success: true, kit: parsedKit }, 200, request, env);
  } catch (e) {
    logError('interview_kit_failed', { session_id, error: e.message });
    return jsonResponse({ message: e.message || 'Gagal menghasilkan Interview Kit. Coba lagi.' }, 500, request, env);
  }
}
