export const ABSTRACTION_TERMS_ID = [
  'stakeholder',
  'operasional',
  'profesionalisme',
  'terstruktur',
  'berkelanjutan',
  'penetrasi pasar',
  'sinergi',
  'efisiensi operasional',
  'koordinasi multitask',
  'proaktif',
  'dinamis',
  'komprehensif',
  'holistik',
  'optimalisasi',
];

export const ABSTRACTION_TERMS_EN = [
  'stakeholder',
  'operational excellence',
  'professionalism',
  'structured',
  'sustainable',
  'market penetration',
  'synergy',
  'operational efficiency',
  'multitask coordination',
  'proactive',
  'dynamic',
  'comprehensive',
  'holistic',
  'optimization',
];

export const SKILL_ALIAS_MAP_ID = {
  'komunikasi bisnis profesional': 'komunikasi klien',
  'negosiasi dan hubungan stakeholder': 'negosiasi penjualan',
  'manajemen hubungan stakeholder': 'komunikasi klien',
  'koordinasi operasional berkelanjutan': 'koordinasi operasional',
  'layanan pelanggan profesional': 'customer service',
  'pengelolaan akun kunci': 'account management',
  'hubungan pelanggan': 'customer service',
  'komunikasi customer': 'komunikasi klien',
  'pengelolaan distribusi': 'distribusi produk',
  'penjualan area': 'penjualan lapangan',
  'koordinasi lintas fungsi': 'koordinasi tim',
  'pengembangan pasar': 'penjualan area',
  'administrasi profesional': 'administrasi',
  'pelayanan pelanggan': 'customer service',
  'hubungan b2b': 'b2b sales',
};

export const SKILL_ALIAS_MAP_EN = {
  'professional business communication': 'client communication',
  'stakeholder relationship management': 'client communication',
  'multitask operational coordination': 'operational coordination',
  'professional customer service': 'customer service',
  'key account relationship management': 'account management',
  'customer relationship handling': 'customer service',
  'distribution management': 'distribution operations',
  'area sales management': 'field sales',
  'cross-functional coordination': 'team coordination',
  'market development': 'territory sales',
  'professional administration': 'administration',
  'b2b relationship management': 'b2b sales',
  'client stakeholder communication': 'client communication',
  'sales negotiation strategy': 'sales negotiation',
  'operational excellence management': 'operations support',
};

